##########################################################################
# generate_qtpro.sh: Generates QtCreator project from folder structure.
# Copyright (C) $(IE_DEV) 2011 - Present. All Rights Reserved.
# 
# History:
#		* 06.05.2014 - Created by James Jhuighuy.
##########################################################################

# Validating arguments
if [ -z "$1" ]; then
	PROJECT_FILE="GoddamnEngine.pro"
    echo "Warning: no target project name specified. Using default project name: $PROJECT_FILE"
	echo "Usage: $0 QtProjectFileName"
fi

# Determining path to GoddamnEngine SDK:
if [ -z "$GODDAMN_SDK" ]; then
	echo 'System variable GODDAMN_SDK was not set. Please check GoddamnEngine SDK installation.'
	echo 'Treating that we are located in $GODDAMN_SDK/source/Build/QtCreator'
	GODDAMN_SDK="./../../.."
fi

# Clearing output project.
echo '' > $PROJECT_FILE

# Printing Copyright.
echo '# Generated by generate_qtpro.sh.'                              >> $PROJECT_FILE
echo '# Copyright (C) $(IE_DEV) 2011 - Present. All Rights Reserved.' >> $PROJECT_FILE
echo ' '                                                              >> $PROJECT_FILE

# Exporting C++ and Qt properties.
echo 'QMAKE_CXXFLAGS += -std=c++11 -O3 -msse4.1 -mssse3 -msse3 -msse2 -msse'>> $PROJECT_FILE # Enabling C++11
echo "INCLUDEPATH    += $GODDAMN_SDK/source/" >> $PROJECT_FILE
echo 'TEMPLATE        = app'                  >> $PROJECT_FILE
echo 'DEFINES        += _DEBUG'				  >> $PROJECT_FILE
echo 'DEFINES        -= UNICODE'		      >> $PROJECT_FILE
echo 'CONFIG         += console'              >> $PROJECT_FILE
echo 'CONFIG         -= app_bundle'           >> $PROJECT_FILE
echo 'CONFIG         -= qt'                   >> $PROJECT_FILE
echo ''                                       >> $PROJECT_FILE

# Exporting C++ and C headers.
echo 'HEADERS += \'                 >> $PROJECT_FILE
for cpp_header in `find $GODDAMN_SDK/source/ -name *.hpp \
										  -o -name *.hxx \
										  -o -name *.hh  \
										  -o -name *.h   \
										  -o -name *.inl`; do
	echo "	$cpp_header \\"     >> $PROJECT_FILE
done
echo '' >> $PROJECT_FILE

# Exporting C++ and C sources.
echo 'SOURCES += \'                 >> $PROJECT_FILE
for cpp_source in `find $GODDAMN_SDK/source/ -name *.cpp -o -name *.cxx -o -name *.cc -o -name *.c`; do
	echo "	$cpp_source \\"     >> $PROJECT_FILE
done
echo '' >> $PROJECT_FILE
