#include <GoddamnEngine/Engine/Resource/Resource.hh>

GD_NAMESPACE_BEGIN
	GD_TYPEINFORMATION_IMPLEMENTATION_C(Resource, Object, GDAPI, nullptr);
	GD_TYPEINFORMATION_IMPLEMENTATION(BinaryResource, Resource, GDAPI, GD_RESOURCE_ARGS);
GD_NAMESPACE_END
